### ISSUE TITLE
dubbo调用的返回值中怎么去掉类名

### ISSUE THREAD

**Issue by caiBird18** [dubbo/jmeter-plugins-for-apache-dubbo#68]
<img width="669" alt="WechatIMG6" src="https://user-images.githubusercontent.com/49863373/56494989-c46ab180-6526-11e9-8eb6-89d92f50e4be.png">

**Comment by ningyu1** [comment]
@caiBird18 返回值中应该没有class，你这个是请求参数把

**Comment by ningyu1** [comment]
@caiBird18 插件采用dubbo泛化调用，调用结果是有class属性的
