### ISSUE TITLE
dubbo rpc 序列化问题

### ISSUE THREAD

**Issue by wychenlong** [dubbo/jmeter-plugins-for-apache-dubbo#71]
{""name":"test",items": {"class": "io.github.ningyu.MyClassVo","name": "123456"}};真正反列话的时候itmes结果真正的放到map里面去了；

**Comment by wychenlong** [comment]
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast ;

**Comment by ningyu1** [comment]
@wychenlong 问题是在调用接口前入参序列化的时候？还是接口调用拿到结果集序列化的时候?

**Comment by wychenlong** [comment]
入参反序列化的时候

**Comment by ningyu1** [comment]
@wychenlong 泛化调用是通过map传参的，map传到服务端会根据map中的class属性进行反序列化，你只需要按照你的参数类型写入参的json格式字符串即可

**Comment by wychenlong** [comment]
是的，已经按照这个传了 只是我 myclassvo 里面的泛型类型对象 T，代码给我转换成map类型，而不是对象类型

**Comment by ningyu1** [comment]
检查jmeter classpath下是否有api jar。
如果有api jar会直接反序列化为参数类型。
如果没有api jar会反序列化通用map，泛化入参都是支持的。

**Comment by wychenlong** [comment]
classpath加了

**Comment by wychenlong** [comment]
用的dubbo2.7那个JAR

**Comment by ningyu1** [comment]
是api jar非dubbo jar，是接口的jar包

**Comment by wychenlong** [comment]
是的，我在classpath引入了我的接口定义的API JAR

**Comment by wychenlong** [comment]
public class CommonRequest<T>
  implements Serializable
{
  private static final long serialVersionUID = 1L;
  public static final String REQUEST_VERSION = "1.0.0";
  private String requestNo;
  private String requestTime;
  private String channelCode;
  private String version;
  private T requestData;


com.alibaba.dubbo.rpc.service.GenericException: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.jd.jr.fintech.megrez.loan.core.api.preloan.request.CreditApplyReqDto
java.lang.ClassCastExceptio

**Comment by wychenlong** [comment]
{
    "requestNo": "outsi2019050215034042067958",
    "requestTime": "20190502150340",
    "channelCode": "CRPL_WANGDAI_ONE",
    "requestData": {
        "class":"com.jd.jr.fintech.megrez.loan.core.api.preloan.request.CreditApplyReqDto",

**Comment by wychenlong** [comment]
你是泛化处理 不需要引入API JAR

**Comment by wychenlong** [comment]
检查jmeter classpath下是否有api jar。
如果有api jar会直接反序列化为参数类型。
如果没有api jar会反序列化通用map，泛化入参都是支持的。

如果使用通用map的参数方式，例如：{"name":"test",items": {"class": "io.github.ningyu.MyClassVo","name": "123456"}} 需要删除classpath下的api jar
如果使用具体类型的参数方式，例如：{"name":"test",items": {"name": "123456"}} 需要在classpath下添加api jar


这个两种方式分别已经试了

**Comment by ningyu1** [comment]
你要是传入`{
"requestNo": "outsi2019050215034042067958",
"requestTime": "20190502150340",
"channelCode": "CRPL_WANGDAI_ONE",
"requestData": {
"class":"com.xxx.CreditApplyReqDto",}}`这种结构的话，就把你接口的jar包从jmeter classpath删除，然后重启jmeter，不重启不生效

**Comment by ningyu1** [comment]
> 你是泛化处理 不需要引入API JAR

插件会优先从classpath下找（接口jar包加入到jmeter classpath），如果没有找到才会使用通用map

问题解决了吗？
