### ISSUE TITLE
是的，已经按照这个传了 只是我 myclassvo 里面的泛型类型对象 T，代码给我转换成map类型，而不是对象类型

### ISSUE THREAD

**Issue by wychenlong** [dubbo/jmeter-plugins-for-apache-dubbo#73]
是的，已经按照这个传了 只是我 myclassvo 里面的泛型类型对象 T，代码给我转换成map类型，而不是对象类型

_Originally posted by @wychenlong in https://github.com/dubbo/jmeter-plugins-for-apache-dubbo/issues/71#issuecomment-489395499_

**Comment by ningyu1** [comment]
刚才的reopen掉就好了，这个close了
