### ISSUE TITLE
Map里包含多种类型的值

### ISSUE THREAD

**Issue by abcwt112** [dubbo/jmeter-plugins-for-apache-dubbo#75]
类似这个问题
https://github.com/dubbo/jmeter-plugins-for-apache-dubbo/issues/61

参数类型是Map<String,Object>
但是value可能是Long也可能是Double.
比如我传数值1,我想指定它是double或者long
请问该怎么设置paramValue? 

谢谢

**Comment by ningyu1** [comment]
@abcwt112 
不用做特殊区分都当做数字传入即可，例如：
{"double类型": 8.2, "long类型": 7}
